version: 2.1

commands:
  test_py27:
    steps:
      - checkout
      - run:
          name: Run tests with Python 2.7
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py27

  build_python_2_7_wheel:
    steps:
      - run:
        name: Build the python2 wheel
        command: python2 setup.py bdist_wheel
        - store_artifacts:
            path: dist/
            destination: circleci-wheels

  test_py37:
    steps:
      - checkout
      - run:
          name: Run tests with Python 3.7
          command: |
            sudo pip install --upgrade pip
            pip install --user tox
            tox -e py37

  build_python_3_7_wheel:
    steps:
      - run:
        name: Build the python3 wheel
        command: python3 setup.py bdist_wheel
        - store_artifacts:
            path: dist/
            destination: circleci-wheels

executors:
  docker_python_2_7:
    docker:
      - image: circleci/python:2.7.18

  docker_python_3_7:
    docker:
      - image: circleci/python:3.7.7

jobs:
  test_python_2_7_environment:
    executor: docker_python_2_7
    working_directory: ~/project
    steps:
      - test_py27
      - build_python_2_7_wheel

  test_python_3_7_environment:
    executor: docker_python_3_7
    working_directory: ~/project
    steps:
      - test_py37
      - build_python_3_7_wheel

workflows:
  version: 2
  tests:
    jobs:
      - test_python_2_7_environment
      - test_python_3_7_environment
